name: Build Tweak

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scheme: [ rootless, roothide ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang lld git wget unzip

    - name: Setup Theos
      run: |
        git clone --depth 1 https://github.com/theos/theos.git $HOME/theos
        curl -LO https://github.com/sbingner/ldid/releases/download/v2.1.5/ldid_2.1.5_ubuntu_focal_amd64.deb
        sudo dpkg -i ldid_2.1.5_ubuntu_focal_amd64.deb

    - name: Build Package
      env:
        THEOS: ${{ github.workspace }}/theos
      run: |
        make clean
        make SCHEME=${{ matrix.scheme }} package

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.scheme }}-package
        path: |
          packages/*.deb
